=== chrisgrieser/.config/karabiner/assets/complex_modifications/schema/karabiner-mod-schema.json
{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"$ref": "#/definitions/KarabinerModSchema",
	"definitions": {
		"KarabinerModSchema": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"title": {
					"type": "string"
				},
				"homepage": {
					"type": "string"
				},
				"rules": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Rule"
					}
				},
				"maintainers": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"anchors": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Anchor"
					}
				}
			},
			"required": [],
			"title": "KarabinerModSchema"
		},
		"Anchor": {
			"type": "object",
			"additionalProperties": true,
			"title": "Anchor"
		},
		"AnchorCondition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"type": {
					"$ref": "#/definitions/ConditionType"
				},
				"bundle_identifiers": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"input_sources": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/InputSource"
					}
				},
				"name": {
					"type": "string"
				},
				"value": {}
			},
			"required": [],
			"title": "AnchorCondition"
		},
		"AnchorManipulator": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"type": {
					"$ref": "#/definitions/ManipulatorType"
				},
				"from": {
					"$ref": "#/definitions/PurpleFrom"
				},
				"to": {
					"type": "array",
					"items": { "$ref": "#/definitions/ToElement" }
				},
				"conditions": {
					"type": "array",
					"items": { "$ref": "#/definitions/PurpleCondition" }
				},
				"to_if_alone": {
					"type": "array",
					"items": { "$ref": "#/definitions/ToElement" }
				},
				"to_if_held_down": {
					"type": "array",
					"items": { "$ref": "#/definitions/ToElement" }
				},
				"parameters": {
					"$ref": "#/definitions/Parameters"
				},
				"to_after_key_up": {
					"type": "array",
					"items": { "$ref": "#/definitions/ToElement" }
				}
			},
			"required": [],
			"title": "AnchorManipulator"
		},
		"PurpleCondition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"type": {
					"$ref": "#/definitions/ConditionType"
				},
				"name": {
					"type": "string"
				},
				"value": {
					"type": "boolean"
				},
				"input_sources": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/InputSource"
					}
				},
				"bundle_identifiers": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"file_paths": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"identifiers": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Identifier"
					}
				}
			},
			"required": [],
			"title": "PurpleCondition"
		},
		"Identifier": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"vendor_id": {
					"type": "integer"
				},
				"product_id": {
					"type": "integer"
				},
				"location_id": {
					"type": "integer"
				}
			},
			"required": [],
			"title": "Identifier"
		},
		"InputSource": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"language": {
					"$ref": "#/definitions/Language"
				}
			},
			"required": [],
			"title": "InputSource"
		},
		"PurpleFrom": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key_code": {
					"type": "string"
				},
				"modifiers": {
					"$ref": "#/definitions/Modifiers"
				},
				"simultaneous": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Simultaneous"
					}
				},
				"pointing_button": {
					"type": "string"
				}
			},
			"required": [],
			"title": "PurpleFrom"
		},
		"Modifiers": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"mandatory": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Mandatory"
					}
				},
				"optional": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Mandatory"
					}
				}
			},
			"required": [],
			"title": "Modifiers"
		},
		"Simultaneous": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key_code": {
					"type": "string"
				},
				"pointing_button": {
					"type": "string"
				}
			},
			"required": [],
			"title": "Simultaneous"
		},
		"Parameters": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"basic.simultaneous_threshold_milliseconds": {
					"type": "integer"
				}
			},
			"required": [],
			"title": "Parameters"
		},
		"ToElement": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"key_code": {
					"type": "string"
				},
				"shell_command": {
					"type": "string"
				},
				"set_variable": {
					"$ref": "#/definitions/SetVariable"
				},
				"set_notification_message": {
					"$ref": "#/definitions/SetNotificationMessage"
				},
				"modifiers": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Mandatory"
					}
				},
				"pointing_button": {
					"type": "string"
				},
				"hold_down_milliseconds": {
					"type": "integer"
				},
				"select_input_source": {
					"$ref": "#/definitions/SelectInputSource"
				},
				"lazy": {
					"type": "boolean"
				},
				"software_function": {
					"$ref": "#/definitions/SoftwareFunction"
				},
				"mouse_key": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"x": { "type": "integer" },
						"y": { "type": "integer" },
						"horizontal_wheel": { "type": "integer" },
						"vertical_wheel": { "type": "integer" }
					}
				}
			},
			"required": [],
			"title": "ToElement"
		},
		"SelectInputSource": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"input_source_id": {
					"$ref": "#/definitions/InputSourceID"
				},
				"input_mode_id": {
					"type": "string"
				},
				"language": {
					"type": "string"
				}
			},
			"required": [],
			"title": "SelectInputSource"
		},
		"SetNotificationMessage": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"id": {
					"$ref": "#/definitions/ID"
				},
				"text": {
					"$ref": "#/definitions/Text"
				}
			},
			"required": [],
			"title": "SetNotificationMessage"
		},
		"SetVariable": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"name": {
					"$ref": "#/definitions/SetVariableName"
				},
				"value": {
					"type": "boolean"
				}
			},
			"required": [],
			"title": "SetVariable"
		},
		"AnchorTo": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"set_variable": {
					"$ref": "#/definitions/SetVariable"
				},
				"set_notification_message": {
					"$ref": "#/definitions/SetNotificationMessage"
				}
			},
			"required": [],
			"title": "AnchorTo"
		},
		"Rule": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"description": {
					"type": "string"
				},
				"manipulators": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/RuleManipulator"
					}
				}
			},
			"required": [],
			"title": "Rule"
		},
		"RuleManipulator": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"description": {
					"type": "string"
				},
				"type": {
					"$ref": "#/definitions/ManipulatorType"
				},
				"from": {
					"$ref": "#/definitions/FluffyFrom"
				},
				"to": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/ToElement"
					}
				},
				"parameters": {
					"basic.simultaneous_threshold_milliseconds": {
						"type": "integer"
					}
				},
				"conditions": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/FluffyCondition"
					}
				},
				"to_if_alone": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/ToElement"
					}
				},
				"to_after_key_up": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/ToElement"
					}
				},
				"to_if_held_down": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/ToElement"
					}
				},
				"to_delayed_action": {
					"type": "object",
					"properties": {
						"to_if_invoked": {
							"type": "array",
							"items": { "$ref": "#/definitions/ToElement" }
						},
						"to_if_canceled": {
							"type": "array",
							"items": { "$ref": "#/definitions/ToElement" }
						}
					}
				}
			},
			"required": [],
			"title": "RuleManipulator"
		},
		"FluffyCondition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"type": {
					"$ref": "#/definitions/ConditionType"
				},
				"input_sources": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/InputSource"
					}
				},
				"bundle_identifiers": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"name": {
					"type": "string"
				},
				"identifiers": {
					"type": "array",
					"items": {
						"type": "object",
						"additionalProperties": false,
						"properties": {
							"vendor_id": {
								"type": "integer"
							},
							"is_keyboard": {
								"type": "boolean"
							},
							"is_built_in_keyboard": {
								"type": "boolean"
							},
							"is_game_pad": {
								"type": "boolean"
							},
							"is_pointing_device": {
								"type": "boolean"
							},
							"product_id": {
								"type": "integer"
							},
							"location_id": {
								"type": "integer"
							}
						}
					}
				},
				"value": {},
				"file_paths": {
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			},
			"required": [],
			"title": "FluffyCondition"
		},
		"FluffyFrom": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"pointing_button": {
					"type": "string"
				},
				"key_code": {
					"type": "string"
				},
				"simultaneous": {
					"key_code": {
						"type": "string"
					}
				},
				"modifiers": {
					"$ref": "#/definitions/Modifiers"
				}
			},
			"required": [],
			"title": "FluffyFrom"
		},
		"SoftwareFunction": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"set_mouse_cursor_position": {
					"$ref": "#/definitions/SetMouseCursorPosition"
				},
				"open_application": {
					"bundle_identifiers": {
						"type": "array",
						"items": {
							"type": "string"
						}
					},
					"file_paths": {
						"type": "array",
						"items": {
							"type": "string"
						}
					}
				}
			},
			"required": [],
			"title": "SoftwareFunction"
		},
		"SetMouseCursorPosition": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"x": {
					"type": "string"
				},
				"y": {
					"type": "string"
				},
				"screen": {
					"type": "integer"
				}
			},
			"required": [],
			"title": "SetMouseCursorPosition"
		},
		"ConditionType": {
			"type": "string",
			"enum": [
				"variable_unless",
				"input_source_unless",
				"variable_if",
				"input_source_if",
				"frontmost_application_if",
				"frontmost_application_unless",
				"device_if",
				"device_unless"
			],
			"title": "ConditionType"
		},
		"Language": {
			"type": "string",
			"enum": ["^de$", "^en$", "^ja$"],
			"title": "Language"
		},
		"Mandatory": {
			"type": "string",
			"enum": [
				"shift",
				"right_shift",
				"left_shift",
				"command",
				"left_command",
				"right_command",
				"option",
				"left_option",
				"right_option",
				"control",
				"left_control",
				"right_control",
				"caps_lock",
				"fn"
			],
			"title": "Mandatory"
		},
		"InputSourceID": {
			"type": "string",
			"title": "InputSourceID"
		},
		"ID": {
			"type": "string"
		},
		"Text": {
			"type": "string"
		},
		"SetVariableName": {
			"type": "string"
		},
		"ManipulatorType": {
			"type": "string",
			"enum": ["basic"],
			"title": "ManipulatorType"
		}
	}
}

=== chrisgrieser/.config/karabiner/assets/complex_modifications/1690028886.json
{
  "title": "Finder Vim Controls",
  "homepage": "https://github.com/chrisgrieser/dotfiles/karabiner",
  "maintainers": [
    "pseudometa (chrisgrieser)"
  ],
  "anchors": [
    {
      "conditions": [
        {
          "type": "frontmost_application_if",
          "bundle_identifiers": [
            "^com\\.apple\\.finder$"
          ]
        },
        {
          "type": "frontmost_application_if",
          "bundle_identifiers": [
            "^com\\.runningwithcrayons\\.Alfred$",
            "^com\\.apple\\.finder$"
          ]
        },
        {
          "type": "input_source_if",
          "input_sources": [
            {
              "language": "^de$"
            }
          ]
        },
        {
          "type": "input_source_unless",
          "input_sources": [
            {
              "language": "^de$"
            }
          ]
        },
        {
          "type": "variable_if",
          "name": "FINDER_INSERT_MODE",
          "value": true
        },
        {
          "type": "variable_unless",
          "name": "FINDER_INSERT_MODE",
          "value": true
        },
        {
          "type": "variable_if",
          "name": "FINDER_FIND_MODE",
          "value": true
        },
        {
          "type": "variable_unless",
          "name": "FINDER_FIND_MODE",
          "value": true
        },
        {
          "type": "variable_if",
          "name": "FINDER_ALFRED_ACTIVE",
          "value": true
        },
        {
          "type": "variable_unless",
          "name": "FINDER_ALFRED_ACTIVE",
          "value": true
        },
        {
          "type": "variable_if",
          "name": "FINDER_MOVE_ACTIVE",
          "value": true
        },
        {
          "type": "variable_unless",
          "name": "FINDER_MOVE_ACTIVE",
          "value": true
        },
        {
          "type": "variable_if",
          "name": "FINDER_CONTEXT_MENU_ACTIVE",
          "value": true
        },
        {
          "type": "variable_unless",
          "name": "FINDER_CONTEXT_MENU_ACTIVE",
          "value": true
        }
      ]
    },
    {
      "to": [
        {
          "set_variable": {
            "name": "FINDER_INSERT_MODE",
            "value": true
          }
        },
        {
          "set_variable": {
            "name": "FINDER_INSERT_MODE",
            "value": false
          }
        },
        {
          "set_notification_message": {
            "id": "insert-notice",
            "text": "‚úèÔ∏è  INSERT"
          }
        },
        {
          "set_notification_message": {
            "id": "insert-notice",
            "text": ""
          }
        },
        {
          "set_variable": {
            "name": "FINDER_FIND_MODE",
            "value": true
          }
        },
        {
          "set_variable": {
            "name": "FINDER_FIND_MODE",
            "value": false
          }
        },
        {
          "set_notification_message": {
            "id": "find-notice",
            "text": "üîç FIND"
          }
        },
        {
          "set_notification_message": {
            "id": "find-notice",
            "text": ""
          }
        },
        {
          "set_notification_message": {
            "id": "move-notice",
            "text": ""
          }
        },
        {
          "set_notification_message": {
            "id": "move-notice",
            "text": "‚úÇÔ∏è  Move active"
          }
        },
        {
          "set_variable": {
            "name": "FINDER_ALFRED_ACTIVE",
            "value": true
          }
        },
        {
          "set_variable": {
            "name": "FINDER_ALFRED_ACTIVE",
            "value": false
          }
        },
        {
          "set_variable": {
            "name": "FINDER_MOVE_ACTIVE",
            "value": true
          }
        },
        {
          "set_variable": {
            "name": "FINDER_MOVE_ACTIVE",
            "value": false
          }
        },
        {
          "set_variable": {
            "name": "FINDER_CONTEXT_MENU_ACTIVE",
            "value": true
          }
        },
        {
          "set_variable": {
            "name": "FINDER_CONTEXT_MENU_ACTIVE",
            "value": false
          }
        }
      ]
    }
  ],
  "rules": [
    {
      "description": "Finder Vim Controls",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "j"
          },
          "to": [
            {
              "key_code": "down_arrow"
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com\\.apple\\.finder$"
              ]
            },
            {
              "type": "variable_unless",
              "name": "FINDER_INSERT_MODE",
              "value": true
            },
            {
              "type": "variable_unless",
              "name": "FINDER_FIND_MODE",
              "value": true
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "k"
          },
          "to": [
            {
              "key_code": "up_arrow"
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com\\.apple\\.finder$"
              ]
            },
            {
              "type": "variable_unless",
              "name": "FINDER_INSERT_MODE",
              "value": true
            },
            {
              "type": "variable_unless",
              "name": "FINDER_FIND_MODE",
              "value": true
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "h"
          },
          "to_if_alone": [
            {
              "key_code": "up_arrow",
              "modifiers": [
                "command"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com\\.apple\\.finder$"
              ]
            },
            {
              "type": "variable_unless",
              "name": "FINDER_INSERT_MODE",
              "value": true
            },
            {
              "type": "variable_unless",
              "name": "FINDER_FIND_MODE",
              "value": true
            },
            {
              "type": "variable_unless",
              "name": "FINDER_CONTEXT_MENU_ACTIVE",
              "value": true
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "l"
          },
          "to_if_alone": [
            {
              "key_code": "down_arrow",
              "modifiers": [
                "command"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com\\.apple\\.finder$"
              ]
            },
            {
              "type": "variable_unless",
              "name": "FINDER_INSERT_MODE",
              "value": true
            },
            {
              "type": "variable_unless",
              "name": "FINDER_FIND_MODE",
              "value": true
            },
            {
              "type": "variable_unless",
              "name": "FINDER_CONTEXT_MENU_ACTIVE",
              "value": true
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "g"
          },
          "to": [
            {
              "key_code": "up_arrow",
              "modifiers": [
                "option"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com\\.apple\\.finder$"
              ]
            },
            {
              "type": "variable_unless",
              "name": "FINDER_INSERT_MODE",
              "value": true
            },
            {
              "type": "variable_unless",
              "name": "FINDER_FIND_MODE",
              "value": true
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "g",
            "modifiers": {
              "mandatory": [
                "shift"
              ]
            }
          },
          "to_if_alone": [
            {
              "key_code": "down_arrow",
              "modifiers": [
                "option"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com\\.apple\\.finder$"
              ]
            },
            {
              "type": "variable_unless",
              "name": "FINDER_INSERT_MODE",
              "value": true
            },
            {
              "type": "variable_unless",
              "name": "FINDER_FIND_MODE",
              "value": true
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "j",
            "modifiers": {
              "mandatory": [
                "shift"
              ]
            }
          },
          "to": [
            {
              "key_code": "down_arrow"
            },
            {
              "key_code": "down_arrow"
            },
            {
              "key_code": "down_arrow"
            },
            {
              "key_code": "down_arrow"
            },
            {
              "key_code": "down_arrow"
            },
            {
              "key_code": "down_arrow"
            }
          ],
          "conditions": [
            {
